create table grades (
  "rStudent"                         text not null,
  "rId"                              integer not null primary key,
  "rLoginID"                         text not null,
  "rSection"                         text not null,
  "rModule1KC"                       decimal,
  "rModule2KC"                       decimal,
  "rModule3KC"                       decimal,
  "rModule4KC"                       decimal,
  "rModule5KC"                       decimal,
  "rModule6KC"                       decimal,
  "rModule7KC"                       decimal,
  "rModule8KC"                       decimal,
  "rModule9KC"                       decimal,
  "rModule10KC"                      decimal,
  "rCourseAssesment"                 decimal,
  "rLab1"                            decimal,
  "rLab2"                            decimal,
  "rLab3"                            decimal,
  "rActivityAwsLambda"               decimal,
  "rActivityElasticBeanstalk"        decimal,
  "rLab4"                            decimal,
  "rLab5"                            decimal,
  "rLab6"                            decimal,
  "rAssignmentsCurrentPoints"        decimal,
  "rAssignmentsFinalPoints"          decimal,
  "rAssignmentsCurrentScore"         decimal,
  "rAssignmentsUnpostedCurrentScore" decimal,
  "rAssignmentsFinalScore"           decimal,
  "rAssignmentsUnpostedFinalScore"   decimal,
  "rKCCurrentPoints"                 decimal,
  "rKCFinalPoints"                   decimal,
  "rKCCurrentScore"                  decimal,
  "rKCUnpostedCurrentScore"          decimal,
  "rKCFinalScore"                    decimal,
  "rKCUnpostedFinalScore"            decimal,
  "rLabsCurrentPoints"               decimal,
  "rLabsFinalPoints"                 decimal,
  "rLabsCurrentScore"                decimal,
  "rLabsUnpostedCurrentScore"        decimal,
  "rLabsFinalScore"                  decimal,
  "rLabsUnpostedFinalScore"          decimal,
  "rCurrentPoints"                   decimal,
  "rFinalPoints"                     decimal,
  "rCurrentScore"                    decimal,
  "rUnpostedCurrentScore"            decimal,
  "rFinalScore"                      decimal,
  "rUnpostedFinalScore"              decimal
);

create table students (
  "rStudent"      text not null primary key,
  "rNombres"      text not null,
  "rApellidos"    text not null
);
